[environments.international]
store = "sportfinder-international.myshopify.com"
ignore = ["config/settings_data.json"]

[environments.czech]
store = "northfinder-cz.myshopify.com"
ignore = ["config/settings_data.json"]

[environments.romania]
store = "northfinder-ro.myshopify.com"
ignore = ["config/settings_data.json"]

[environments.perfumes]
store = "northfinder-parfums.myshopify.com"
ignore = ["config/settings_data.json"]
