[environments.development]
store = "https://northfinder-1.myshopify.com/"

[environments.dev-pl]
store = "https://https://poland-northfinder-2.myshopify.com/"

[environments.perfumes]
store = "northfinder-parfums.myshopify.com/"