[environments.development]
store = "sportfinder-international.myshopify.com"

[environments.germany]
store = "northfinder-1.myshopify.com"

[environments.poland]
store = "poland-northfinder-2.myshopify.com"

[environments.perfumes]
store = "northfinder-parfums.myshopify.com"
